# Generated by Django 3.1 on 2020-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200825_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Send Email to every User',
                'verbose_name_plural': 'Broadcast Email',
            },
        ),
    ]
