# Generated by Django 3.1 on 2020-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='area',
            field=models.CharField(default='e.g: Shalom str, Fagba, Lagos, Nigeria', max_length=255),
        ),
        migrations.AddField(
            model_name='update',
            name='description',
            field=models.TextField(default='Something is going on here', help_text="What's happening there"),
        ),
        migrations.AlterField(
            model_name='update',
            name='matter',
            field=models.CharField(choices=[('Campaign', 'CAMPAIGN'), ('Emergency', 'EMERGENCY'), ('Good news', 'GOOD NEWS'), ('Ceremony', 'CEREMONY'), ('Rumour', 'RUMOUR'), ('Story', 'STORY')], default='Good news', max_length=10),
        ),
    ]
